spring:
  profiles: local
  profiles.include: common, local
---
spring:
  profiles: dev
  profiles.include: common, dev
---
spring:
  profiles: prod
  profiles.include: common, prod
---
spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:local}

info.build:
  version: 1.0.0